"""Initial.

Revision ID: 885068725905
Revises: sebah12
Create Date: 2023-08-23 15:21:44.422587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '885068725905'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('code', sa.String(length=20), nullable=False),
                    sa.Column('title', sa.String(length=250), nullable=False),
                    sa.Column('author', sa.String(length=125), nullable=False),
                    sa.Column('href', sa.String(length=125), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('prices',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.Column('date', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('item_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prices')
    op.drop_table('items')
    # ### end Alembic commands ###
